databases:
  - name: cloudEsgi
    databaseName: cloudesgi 
    user: cloudsgi 

services:
  - type: web
    runtime: node
    name: cloudEsgi
    repo: https://github.com/R-Mehdi94/cloudEsgi
    buildCommand: npm install 
    startCommand: npm run start
    envVars:
      - key: BDDURL
        fromDatabase: 
          name: cloudEsgi
          property: connectionString